services:
    frontend:
      build:
        context: ./static_html
        dockerfile: static.Dockerfile
      ports:
        - 8000:8000
      volumes:
        - ./static_html/src:/app
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 8001:8001
      command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
      environment:
        - PORT=8000
        - MY_PROJECT_NAME=containarize_agent
      env_file:
        - .env
      volumes:
        - ./backend/src:/app
      develop:
        watch:
          - action: rebuild
            path: backend/requirements.txt
          - action: rebuild
            path: backend/Dockerfile
          - action: sync+restart
            path: backend/src/
            target: /app
      depends_on:
        - db_service
    db_service:
      image: postgres:17.5
      ports:
        - "5432:5432"
      volumes:
        - dc_managed_db_data:/var/lib/postgresql/data
      env_file:
        - .env.example_db


volumes:
  dc_managed_db_data:
